### PR TITLE
Lives count

### PR DESCRIPTION
**Pull request by luoyang9**
Untitled

### CODE REVIEW

**Comment by mrdofu** [comment]
what about lives counters in the corners for each player?
Might be easier to track with less movign around

**Comment by luoyang9** [comment]
Untitled

**Comment by mrdofu** [comment]
I know the main map is designed for 16:9, so did you shrink the map width or does this overlay on top?

**Comment by luoyang9** [comment]
I changed the canvas render mode to screen space - camera. so the canvas fill the camera.

**Comment by mrdofu** [comment]
im seeing this. Did you add the correct meta files?
image

**Comment by luoyang9** [comment]
It's showing fine on mine.

**Comment by mrdofu** [comment]
image

**Comment by luoyang9** [comment]
Ok, apparently the gitignore had Assets/TextMeshPro ignored. I added the whole folder, see if it works now

**Comment by mrdofu** [comment]
I think even the text on the right should be left-aligned so that when lives disappear, the label is in the same spot

**Pull request merged**
