### PR TITLE
Adjust wall jump

### PR DESCRIPTION
**Pull request by luoyang9**
Make wall jump jump more so it feels you actually jumping off of a wall.

### CODE REVIEW

**Comment by mrdofu** [comment]
this messes up melee when on the wall

**Comment by luoyang9** [comment]
Fixed

**Comment by mrdofu** [comment]
Ok that fix is bad code. Just let melee go into the wall when wall sliding. If we need it (unlikely), we can add it later

**Comment by luoyang9** [comment]
Wait, what was the mess up then

**Comment by mrdofu** [comment]
kinda useless to have melee go into the wall when you're clinging on the wall (you expect it to go out), but the fix you had `ForceFacing = machine.CurrentState == WALL_SLIDE_STATE ? -Facing : Facing;` is not good code. I'm looking into this too, but If we don't find a better fix today, we can just let the melee attack into the wall.

**Comment by mrdofu** [comment]
Ok I fixed the wall slide thing. Make this diff just the wall jump feel code

**Pull request merged**
